language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

services:
  - postgresql

before_script:
  - psql -U postgres < $TRAVIS_BUILD_DIR/dbscripts.sql

script:
  - cd microservice-database && mvn clean package