---
- hosts: localhost
  tasks:
  - git:
      repo: "https://github.com/airavata-courses/alpha.git"
      dest: "{{playbook_dir}}/stocks"
      version: ms-stocks 
      force: yes
  - git:
      repo: "https://github.com/airavata-courses/alpha.git"
      dest: "{{playbook_dir}}/react-ui"
      version: react-ui
      force: yes
  - git:
      repo: "https://github.com/airavata-courses/alpha.git"
      dest: "{{playbook_dir}}/news"
      version: ms-news
      force: yes
  - git:
      repo: "https://github.com/airavata-courses/alpha.git"
      dest: "{{playbook_dir}}/weather"
      version: ms-weather
      force: yes
  - name: "Install Maven"
    homebrew:
      name: maven
      state: installed
  - name: Install Virtual Env
    pip:
      name: virtualenv
  - name: Install Python Modules
    pip: 
      requirements: "{{playbook_dir}}/news/requirements.txt"
      virtualenv: "{{playbook_dir}}/news/myenv"
      virtualenv_python: python2
  - name: "Install node"
    homebrew:
      name: node
      state: installed
  - name: "Install npm packages for Node"
    npm:
      path: "{{playbook_dir}}/stocks/stock-ms" 
  - name: "Install react"
    shell: npm install -g create-react-app
  - name: "unset pythonpath"
    shell: unset PYTHONPATH
  - name: "Install react-scripts"
    shell: cd {{playbook_dir}}/react-ui/react-ui && npm install --save react-scripts 
  - name: "Start stocks api"
    shell: cd {{playbook_dir}}/stocks/stock-ms && node server.js >/dev/null 2>&1 &
  - name: "Start weather"
    shell: cd {{playbook_dir}}/weather && mvn clean package && java -jar target/microservice-weather-1.0-SNAPSHOT.jar >/dev/null 2>&1 &
  - name: "Start news api "
    shell: "{{playbook_dir}}/news/myenv/bin/python {{playbook_dir}}/news/app.py >/dev/null 2>&1 &"
  - name: "start react ui"
    shell: cd {{playbook_dir}}/react-ui/react-ui && npm start >/dev/null 2>&1 &
