apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 3
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          imagePullPolicy: Always
          image: aishwaryadhage95/ms-db:1.0.0
          env:
            - name: DB_USER
              value: "demo"
            - name: DB_PASSWORD
              value: "p@ssw0rd"
          ports:
            - containerPort: 9101
