version: '2'

services:
    db:
      build: './test_postgres'
      restart: always
      ports:
        - "5433:5432"
      environment:
        POSTGRES_USER: demo
        POSTGRES_PASSWORD: p@ssw0rd
      networks: 
        - host
    ms:
      build: '.'
      ports:
        - "9100:9101"
      links:
        - db
      depends_on:
        - db
      networks: 
        - host
networks:
   host:
      driver: "bridge"
