apiVersion: v1
kind: Service
metadata:
  name: news
spec:
  type: NodePort
  selector:
    app: news
  ports:
      # Port accessible inside cluster
    - port: 5000
      # Port to forward to inside the pod
      targetPort: 5000
      # Port accessible outside cluster
      nodePort: 30002
