apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: NodePort
  selector:
    app: db
  ports:
      # Port accessible inside cluster
    - port: 9101
      # Port to forward to inside the pod
      targetPort: 9101
      # Port accessible outside cluster
      nodePort: 30003
