apiVersion: v1
kind: Service
metadata:
  name: weather
spec:
  type: NodePort
  selector:
    app: weather
  ports:
      # Port accessible inside cluster
    - port: 9102
      # Port to forward to inside the pod
      targetPort: 9102
      # Port accessible outside cluster
      nodePort: 30001
