apiVersion: v1
kind: Service
metadata:
  name: react
spec:
  type: NodePort
  selector:
    app: react
  ports:
      # Port accessible inside cluster
    - port: 3000
      # Port to forward to inside the pod
      targetPort: 3000
      # Port accessible outside cluster
      nodePort: 30005
