apiVersion: v1
kind: Service
metadata:
  name: stocks
spec:
  type: NodePort
  selector:
    app: stocks
  ports:
      # Port accessible inside cluster
    - port: 8000
      # Port to forward to inside the pod
      targetPort: 8000
      # Port accessible outside cluster
      nodePort: 30004
